name: "Ping Webhook"
on:
  workflow_dispatch:

jobs:
  dispatch:
    name: Call Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Call Webhook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ variables.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{"key":"value", "key2":"value2"}'
          verbose: true
